run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - staticcheck

issues:
  exclude-use-default: false