services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ENV=production
      - DB_PATH=/data/chat.db
      - OLLAMA_HOST=ollama:11434
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - MAX_CONCURRENT_CHATS=100
      - READ_TIMEOUT=30s
      - WRITE_TIMEOUT=30s
    volumes:
      - chat_data:/data
    depends_on:
      - ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - chat_ollama_network
    security_opt:
      - no-new-privileges:true

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - chat_ollama_network

volumes:
  chat_data:
    driver: local
  ollama_models:
    driver: local

networks:
  chat_ollama_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16