version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - DB_PATH=/data/chat.db
      - OLLAMA_HOST=ollama:11434
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - MAX_CONCURRENT_CHATS=100
      - READ_TIMEOUT=30s
      - WRITE_TIMEOUT=30s
    volumes:
      - chat_data:/data
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - chat_ollama_network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - chat_ollama_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  chat_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  ollama_models:
    driver: local

networks:
  chat_ollama_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16